# Generated by Django 4.1.1 on 2022-09-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
